<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<whydahuser>
    <identity>
        <username>leon</username>
        <cellPhone>123456</cellPhone>
        <email>leon.ho@test.com</email>
        <firstname>Leon</firstname>
        <lastname>Ho</lastname>
        <personRef>1</personRef>
        <UID>leon.ho@test.com</UID>
    </identity>
    <applications>
        <application>
            <appId>3</appId>
            <applicationName>Whydah</applicationName>
            <orgID>1</orgID>
            <roleName>developer</roleName>
            <roleValue>20</roleValue>
        </application>
        <application>
            <appId>1</appId>
            <applicationName>UserAdmin</applicationName>
            <orgID>1</orgID>
            <roleName>UserAdmin</roleName>
            <roleValue></roleValue>
        </application>
        <application>
            <appId>2</appId>
            <applicationName>Mobilefirst</applicationName>
            <orgID>5</orgID>
            <roleName>client</roleName>
            <roleValue>10</roleValue>
        </application>
        <application>
            <appId>4</appId>
            <applicationName>ACS</applicationName>
            <orgID>5</orgID>
            <roleName>Administrator</roleName>
            <roleValue>true</roleValue>
        </application>
        <application>
            <appId>3</appId>
            <applicationName>Whydah</applicationName>
            <orgID>1</orgID>
            <roleName>WhydahUserAdmin</roleName>
            <roleValue>99</roleValue>
        </application>
        <application>
            <appId>4</appId>
            <applicationName>ACS</applicationName>
            <orgID>5</orgID>
            <roleName>Manager</roleName>
            <roleValue></roleValue>
        </application>
        <application>
            <appId>4</appId>
            <applicationName>ACS</applicationName>
            <orgID>5</orgID>
            <roleName>Employee</roleName>
            <roleValue>Leon.Ho@altran.com</roleValue>
        </application>
    </applications>
</whydahuser>
